export const defaultValuePaciente = {
  nome: "",
  cns: "",
  sexo: "",
  tel: "",
  dataNasc: null,
  dataInsc: null,
  recadastro: "",
  convenio: "",
  esf: "",
  escolaridade: "",
  profissao: "",
  mobilidade: "",
  renda: "",
  condicoes: [],
  ativo: true,
  motivoInatividade: "",
};

export const defaultValueCirurgia = {
  tipo: "",
  data: null,
  hospital: "",
  paciente: "",
  medico: "",
  crm: "",
  uf: "",
};
export const defaultValueEstoma = {
  paciente: "",
  tipo: "",
  cid: "",
  doenca: "",
  demarcacao: "",
  exteriorizacao: "",
  abdome: "",
  permanencia: "",
  indeterminadoMotivo: "",
  localizacao: "",
  higiene: "",
  formato: "",
  forma: "",
  coloracao: "",
  haste: "",
  protusao: "",
  funcional: "",
  complicacao: [],
  efluente: [],
  periestoma: [],
  cinto: "",
};
export const defaultValueRecebedor = {
  nome: "",
  cpf: "",
  sexo: "",
  paciente: "",
  tel: "",
  orgao: "",
};
export const defaultValueConsulta = {
  data: null,
  hospital: "",
  paciente: "",
  status: "Pendente",
};
export const defaultValueEquipamento = {
  diâmetro: "",
  sistemaQtd: "",
  sistemaOpacidade: "",
  sistemaDrenavel: "",
  tipoPlaca: "",
  placaRecortavel: "",
  adjuvante: "",
  custoExtra: "",
  equipamento: "",
  adaptacao: "",
  obs: "",
  paciente: "",
  estoma: "",
};
